config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "posts#index"
  post '/', to: 'posts#index'
  get "about", to: "posts#about"
  get "likes/liked_posts/:id", to: "likes#liked_posts"

  resources :users, only: [:show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:index, :create, :show, :index]
  resources :posts, only: [:index, :create, :show, :update, :destroy] do
    resources :likes, only: [:index, :create, :destroy]
  end

  
  # resources :searches, only: [:index]
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!, only: [:index]

  def index
    @likes = Post.find(params[:post_id]).liked_users.order("id DESC").page(params[:page]).per(10)

    if user_signed_in? && current_user.name == nil || user_signed_in? && current_user.introduce == nil || user_signed_in? && current_user.name == "" || user_signed_in? && current_user.introduce == ""
      redirect_to profile_edit_path
    end
  end

  def liked_posts
    @likes = User.find(params[:id]).liked_posts.order("id DESC").page(params[:page]).per(10)

    if user_signed_in? && current_user.name == nil || user_signed_in? && current_user.introduce == nil || user_signed_in? && current_user.name == "" || user_signed_in? && current_user.introduce == ""
      redirect_to profile_edit_path
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.create(post_id: params[:post_id])
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    # redirect_back(fallback_location: root_path)
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(post) %>
    <%= link_to post_like_path(post, current_user), method: :delete, remote: true, class: "icon-link" do %>
      <i class="fas fa-heart icon"></i>
    <% end %>
    <span class="likes-count icon"><%= post.likes.count %></span>
  <% else %>
    <%= link_to post_likes_path(post), method: :post, remote: true, class: "icon-link" do %>
      <i class="far fa-heart icon"></i>
    <% end %>
    <span class="likes-count icon"><%= post.likes.count %></span>
  <% end %>
<% else %>
  <% if post.likes.count != 0 %>
    <i class="fas fa-heart icon"></i>
    <span class="likes-count"><%= post.likes.count %></span>
  <% else %>
    <i class="far fa-heart icon"></i>
    <span class="likes-count"><%= post.likes.count %></span>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

$('#number_like_<%= @post.id %>').html("<%= @post.likes.count %>件のいいね");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

$('#number_like_<%= @post.id %>').html("<%= @post.likes.count %>件のいいね");

app/views/likes/index.html.erb
<div class="likes-index">
  <div class="container">
    <div class="row">
      <div class="col-md-2">

      </div>

      <div class="col-md-8">
        <h2>いいねされました</h2>
        <% @likes.each do |like| %>
          <%= link_to user_path(like.id), class: "link-block" do %>
            <div class="profiles">
              <div class="field">
                <span>名前：</span>
                <span><%= like.name %></span>
              </div>
                <% if current_user.persisted? && current_user.image? %>
                  <% if like.image? %>
                    <%= image_tag like.image.to_s, class: "icon" %>
                  <% else %>
                    <%= image_tag '/no_image.png', class: "icon" %>
                  <% end %>
                <% else %>
                  <% if like.image? %>
                    <%= image_tag like.image.to_s, class: "icon" %>
                  <% else %>
                    <%= image_tag '/no_image.png', class: "icon" %>
                  <% end %>
                <% end %>
              <div class="field">
                <span>年齢：</span>
                <span><%= like.age %>歳</span>
              </div>
              <div class="field">
                <span>自己紹介（お肉への熱い想い）:</span>
                <span><%= like.introduce %></span>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="pagenation">
          <%= paginate @likes %>
        </div>
      </div>

      <div class="col-md-2">

      </div>
    </div>
  </div>
</div>

app/views/likes/liked_posts.html.erb
<div class="likes-liked_posts">
  <div class="index-field">
    <div class="container">
      <div class="row">
        <h2>いいね一覧</h2>
        <div class="col-md-12">
          <% @likes.each do |post| %>
            <div class="post-field col-md-12">
              <div class="post-time">
                <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
              </div>
              <div class="my-block">
                <% if user_signed_in? %>
                  <% if current_user.persisted? && current_user.image? %>
                    <% if post.user.image? %>
                      <a class="user-icon" href="<%= user_path(id: post.user_id) %>">
                        <%= image_tag post.user.image.to_s, class: "icon" %>
                      </a>
                      <a class="user" href="<%= user_path(id: post.user_id) %>">
                        <%= post.user.name %>
                      </a>
                    <% else %>
                      <a class="user-icon" href="<%= user_path(id: post.user_id) %>">
                        <%= image_tag '/no_image.png', class: "icon" %>
                      </a>
                      <a class="user" href="<%= user_path(id: post.user_id) %>">
                        <%= post.user.name %>
                      </a>
                    <% end %>
                  <% else %>
                    <% if post.user.image? %>
                      <a class="user-icon" href="<%= user_path(id: post.user_id) %>">
                        <%= image_tag post.user.image.to_s, class: "icon" %>
                      </a>
                      <a class="user" href="<%= user_path(id: post.user_id) %>">
                        <%= post.user.name %>
                      </a>
                    <% else %>
                      <a class="user-icon" href="<%= user_path(id: post.user_id) %>">
                        <%= image_tag '/no_image.png', class: "icon" %>
                      </a>
                      <a class="user" href="<%= user_path(id: post.user_id) %>">
                        <%= post.user.name %>
                      </a>
                    <% end %>
                  <% end %>
                <% else %>
                  <% if post.user.image? %>
                    <a class="user-icon" href="<%= user_path(id: post.user_id) %>">
                      <%= image_tag post.user.image.to_s, class: "icon" %>
                    </a>
                    <a class="user" href="<%= user_path(id: post.user_id) %>">
                      <%= post.user.name %>
                    </a>
                  <% else %>
                    <a class="user-icon" href="<%= user_path(id: post.user_id) %>">
                      <%= image_tag '/no_image.png', class: "icon" %>
                    </a>
                    <a class="user" href="<%= user_path(id: post.user_id) %>">
                      <%= post.user.name %>
                    </a>
                  <% end %>
                <% end %>
              </div>
              <div class="post-block">
                <div class="first-block">
                  <div class="restaurant-field">
                    <span >お店の名前</span><br>
                    <%= link_to post.restaurant_name, post.url, class: "restaurant-name", target: "_blank" %>
                  </div>

                  <div class="field">
                    <span><%= image_tag post.image.to_s, class: "meat-image" %></span>
                  </div>
                </div>
                <div class="second-block">
                  <!-- <div class="field">
                    <span class="title">リンク</span><br>
                    <span>　<a href="<%= post.url %>" target="_blank"><%= post.url %></a></span>
                  </div> -->

                  <div class="field">
                    <span class="title">住所</span><br>
                    <span>　<%= post.address %></span>
                  </div>

                  <div class="field">
                    <span class="title">ジャンル</span><br>
                    <span>　<%= post.genre %></span>
                  </div>

                  <div class="field">
                    <span class="title">評価</span><br>
                    　
                    <span class="average-star" score="<%= post.average %>"></span>
                    <span><%= post.average %></span>
                  </div>

                  <div class="field reputation-field">
                    <span class="title">口コミ</span><br>
                    　
                    <span><%= post.reputation %></span>
                  </div>

                  <div class="posts-show-like">
                    <a href="/posts/<%= post.id %>/likes" class="number-likes" id="number_like_<%= post.id %>"><%= post.likes.count %>件のいいね</a>
                    <div class="posts-show-like-icon">
                      <div id="likes_buttons_<%= post.id %>">
                        <%= render partial: 'likes/like', locals: { post: post } %>
                      </div>

                      <%= link_to "詳細", post_path(post.id), class: "syosai" %>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="pagenation">
      <%= paginate @likes %>
    </div>
  </div>
</div>








<script type="text/javascript">
  window.addEventListener('turbolinks:load',()=>{
    console.log("index");
    const allStars = $(".average-star")
    allStars.each((_, elem)=>{
      const stars = $(elem)
      stars.raty({
        path: "/",
        readOnly: true,
        score: stars.attr("score")
      })
    })
  });
</script>