config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root "posts#index"
  post '/', to: 'posts#index'
  get "about", to: "posts#about"
  get "likes/liked_posts/:id", to: "likes#liked_posts"

  resources :users, only: [:show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:index, :create, :show, :index]
  resources :posts, only: [:index, :create, :show, :update, :destroy] do
    resources :likes, only: [:index, :create, :destroy]
  end

  
  # resources :searches, only: [:index]
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end

    @anotherEntries = Message.where(room_id: myRoomIds).order(created_at: "DESC").uniq { |m| m.room_id }.map{|e| e.room.entries.find_by("user_id != ?", current_user.id)}
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_chat.html.erb
<div class="message-block">
  <% if messages.present? %>
    <% messages.each do |m| %>
      <% if user_signed_in? && current_user.id == m.user_id %>
        <div class="my-messages">
          <div class="my-message-block">
            <span class="my-message"><%= m.content %></span><br>
            <span class="send-time"><%= m.created_at.strftime('%Y/%m/%d %H:%M') %></span>
          </div>
          <%= link_to user_path(m.user_id), class: "icon-link" do %>
            <%= image_tag m.user.image.to_s, class: "icon" %>
          <% end %>
        </div>
      <% else %>
        <div class="your-messages">
          <%= link_to user_path(m.user_id), class: "icon-link" do %>
            <%= image_tag m.user.image.to_s, class: "icon" %>
          <% end %>
          <div class="your-message-block">
            <span class="your-message"><%= m.content %></span><br>
            <span class="send-time"><%= m.created_at.strftime('%Y/%m/%d %H:%M') %></span>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <h3 class="text-center">メッセージはまだありません</h3>
  <% end %>
</div>

app/views/rooms/_send.html.erb
<%= form_for message, remote: true do |f| %>
  <%= f.text_field :content, class: "message-submit-block form-control", :placeholder => "メッセージを入力して下さい" %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <%= button_tag type: 'submit', class: "btn btn-danger",id: "message_btn" do %>
    <i class="far fa-paper-plane"></i>
  <% end %>
<% end %>

app/views/rooms/index.html.erb
<div class="rooms-index">
  <div class="container">
    <div class="row">
      <div class="col-md-3">

      </div>

      <div class="col-md-6 message-users">
        <h2>メッセージ一覧</h2>
        <% @anotherEntries.each do |e| %>
          <!-- <div class="message-user"> -->
            <%= link_to room_path(e.room.id), class: "link" do %>
              <%= image_tag e.user.image.to_s, class: "icon" %>
              <span class="user-name"><%= e.user.name %></span>
            <% end %>
          <!-- </div> -->
        <% end %>
      </div>

      <div class="col-md-3">

      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="rooms-show">
  <div class="container">
    <div class="row">
      <div class="col-md-3">

      </div>

      <div class="col-md-6">
        <div class="messages-field">
          <div class="your-name-block">
            <% @entries.each do |e| %>
              <% unless user_signed_in? && current_user.id == e.user_id %>
                <h4 class="message-user"><strong><a href="/users/<%= e.user.id %>"><%= e.user.name %></a></strong></h4>
              <% end %>
            <% end %>
          </div>
          <div id="message-block-js">
            <%= render partial: 'chat', locals: { messages: @messages } %>
          </div>
          <div class="message-submit-field">
            <div id="sends_buttons">
              <%= render partial: 'send', locals: { message: @message } %>
            </div>

          </div>
        </div>
      </div>
      <div class="col-md-3">

      </div>
    </div>
  </div>
</div>

<script>
  $(function(){
    $("#message-block-js").animate({ scrollTop: $("#message-block-js")[0].scrollHeight}, "slow");
    $("#message_btn").click(function(){
      $("#message-block-js").animate({ scrollTop: $("#message-block-js")[0].scrollHeight}, "slow");
    })
  });
</script>